# Generated by Django 2.0.1 on 2018-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=200)),
                ('L_name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('zipcode', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
