# Generated by Django 2.0.1 on 2018-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0002_general_registration_organization_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_registration',
            name='gender',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
