# Generated by Django 2.0.2 on 2018-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0008_content_file_image_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='None', upload_to='images'),
        ),
    ]
