# Generated by Django 2.0.2 on 2018-02-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0009_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='None', upload_to='video'),
        ),
    ]
