# Generated by Django 2.0.1 on 2018-04-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0011_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='question',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='PLCert.Question'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
