# Generated by Django 2.0.1 on 2018-04-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0012_auto_20180420_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='PLCert.Module'),
        ),
    ]
