# Generated by Django 2.0.1 on 2018-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLCert', '0013_auto_20180420_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
    ]
